"""Stable CLI launchers for installed Orrery release bundles."""

from __future__ import annotations


def launcher_script(tool: str, binary: str) -> str:
    """Return a POSIX launcher with opt-in, local-only timing telemetry.

    The generated script deliberately records no command arguments, working
    directory, output, or environment values.  When timing is disabled it
    immediately execs the verified payload, preserving the CLI's exit status
    and signal behaviour.
    """

    payload = f".orrery-{tool}.payload/{binary}/{binary}"
    return f'''#!/bin/sh
# Generated by orrery-upgrade. Set ORRERY_CLI_TIMING=1 for local timing JSONL.
set -u
launcher_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
target="$launcher_dir/{payload}"

case "${{ORRERY_CLI_TIMING:-}}" in
  1|true|TRUE|yes|YES)
    umask 077
    state_root="${{XDG_STATE_HOME:-${{HOME:-/tmp}}/.local/state}}"
    log="${{ORRERY_CLI_TIMING_LOG:-$state_root/orrery/cli-timing.jsonl}}"
    log_dir=$(dirname -- "$log")
    mkdir -p "$log_dir" 2>/dev/null || exec "$target" "$@"
    if [ -f "$log" ] && [ "$(wc -c < "$log" 2>/dev/null || echo 0)" -ge 5242880 ]; then
      mv -f "$log" "$log.1" 2>/dev/null || :
    fi
    timing_file=$(mktemp "${{TMPDIR:-/tmp}}/orrery-cli-timing.XXXXXX") || exec "$target" "$@"
    started_at=$(/bin/date -u '+%Y-%m-%dT%H:%M:%SZ')
    /usr/bin/time -p -o "$timing_file" "$target" "$@"
    exit_code=$?
    duration_ms=$(awk '/^real / {{ printf "%d", ($2 * 1000) + 0.5; found=1 }} END {{ if (!found) print 0 }}' "$timing_file")
    rm -f "$timing_file"
    printf '{{"schema":1,"tool":"{tool}","entrypoint":"{binary}","started_at":"%s","duration_ms":%s,"exit_code":%s}}\n' \
      "$started_at" "$duration_ms" "$exit_code" >> "$log" 2>/dev/null || :
    exit "$exit_code"
    ;;
esac

exec "$target" "$@"
'''
