name: Release

on:
  pull_request:
  workflow_dispatch:
  push:
    tags: ["v*"]

jobs:
  release:
    permissions:
      contents: write
    uses: the-orrery/.github/.github/workflows/python-release.yml@v10
